language: java
jdk:
  - oraclejdk8
  - openjdk11
notifications:
  email: false
env:
  global:
  - secure: Kh4oQtR4rkzT7FJ5grPlgN7d16vy7ycJ4eu/t+i0glepmyceItqFvlK7Ltp+Rq1c6DjIAALPcmnunwUImXBYvtdfqQn8/uTi66yd7eBjpdw7FHSfws64lLz2rTx0VRFPfPcJxfrh/qS9xb0oZazI4F7XwYtbKqIuMuMiqWlpvVwHR5fg17e0M6tX5Q+xTwCYSdFomMW6afLwXS118bD7tFuuhAk8YVj0q/1trLgKTzaWdoEUqqrCFMiihJscqZZHFBarbrMItdf5NpJA3obcJSDbQGo1aVV83nU4H/NHinqL8X287jBUzDtZcxR6PZN1qtZB0cHD3HoLOV37ZSVkD62yBXYA5LtJ3kLK0ppJUQqd5uz4JZs3hkOhdod3jRSwALg/2NU5kDNMXfHdpGtk10DMG8JwTu200cs9+FMdKQOjixQHcAzaMwD9cJMvSkWqfRvAcGxC6ltskfJ5RTxQGfeBsxVpG7FkerxfBvPgjG5n4yjKf4QtxoqJVCeohZpGxDUR7VXfmehu8jpM3IT9OwR1V9tM+xlcEXVugY/P5IKoQM+A+aSgLDeZ5p85tr36eces1klTlQXFjtf/QH5JO/zNZurG9iAe28OmhaHgHoswndApcRlhqmVJYXhdcHKMHKeRN9QMtZUJbKeYuDgNZV6p2nK3AQqT4ww/SDvAuSE=
  - secure: pAlhe6TAXTb4wIyy1+l//bI8FuT1L/s0g6aIsvpZTLMG8q3GjBPSXTEgcmE8c4/kCinzaDJD/+q5tN2lTf/vFJB0yUhv+F3x/eyOIo0wxQ5A+o1iG1D+KgsKKVxcshn3x2VDWLjHoWDrdwBmQMG4AICsMM0+Jh7+K0VCCQN8vMXXHikNvK/YgBiDvH2/IOIB1Zn/ZbxTuvKIyMgyB0DFyqHKus1zNbJe7j3WHd7zJVnRszxhW/f7PlYC4XXY7U82gnEe4fffwQsu7yQj+63QLFQjrMTYYu47oAh4243j1HGrHvKEYWQ36dk3/YhgYWCtTltTJqkW5LAAwBhRQomsYrcKXd2mjbGF9GO7znAOHoNYX9qAizA6eHsDbRjk7o24vhzMwZ7E5FBRWYwv+rRkoj+1sUjLaL5Q0ueo3D3CNRwHJyOpquQMiyBG1y3roI+N+4TpgOj4A5rWNLdk8tN1mQLSFIomDYzuugFCEAimBUep+MXXmmJBnGwGT01YEF9HgJvydKrN7GAnvvrlwXHD/QAu5GT4ruODX6+3zLBuhO8830+JpIYjC3yy3PVivWMbVt2poJL894eoDy7w7KNNKLkCOh8X6lar7dAXhYmpGkMli4hV0E9WZ1CQrvsQRU+Vr9QopRu8pcxol+2QEtHwUeG1OF9Mjz/xm+xhqPIStI8=
deploy:
  - provider: script
    script: mvn deploy --settings .travis.settings.xml -DskipTests=true --batch-mode
    skip_cleanup: true
    on:
      tags: false
